version: "3"

services:

  logocontainer:
    image: dockeriscool/demoimage:latest
    environment:
      - TEAM_NAME="superTeam"
    networks:
      - proxy

  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "8088:8080"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

  portainer:
    image: portainer/portainer
    ports:
      - "8090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
    command: -H unix:///var/run/docker.sock
    networks:
      - proxy

networks:
  proxy:
    external: true
