version: "3"

services:

  fotoshow:
    image: dockermgeo/fotos_dockerconeu17:latest
    ports:
      - "8082:80"
    networks:
      - proxy

  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

networks:
  proxy:
    external: true
